
import { Language } from './types';

export const UI_TEXT: Record<Language, Record<string, string>> = {
    EN: {
        title: 'Phishguard',
        login: 'Login',
        signup: 'Sign Up',
        email: 'Email Address',
        password: 'Password',
        noAccount: "Don't have an account?",
        haveAccount: 'Already have an account?',
        checkerTitle: 'Email Phishing Checker',
        checkerSubtitle: 'Paste the full email content or upload an email file (.eml, .txt) to check for phishing threats.',
        pastePlaceholder: 'Paste your email content here...',
        uploadFile: 'Upload File',
        analyze: 'Analyze Email',
        analyzing: 'Analyzing...',
        result: 'Analysis Result',
        safe: 'Safe',
        suspicious: 'Suspicious',
        phishing: 'Phishing',
        poweredBy: 'Analysis powered by Random Forest & Blacklist Algorithms with >98% accuracy.',
        error: 'An error occurred during analysis. Please try again.',
        logout: 'Logout',
    },
    ES: {
        title: 'Phishguard',
        login: 'Iniciar Sesión',
        signup: 'Registrarse',
        email: 'Dirección de Correo Electrónico',
        password: 'Contraseña',
        noAccount: '¿No tienes una cuenta?',
        haveAccount: '¿Ya tienes una cuenta?',
        checkerTitle: 'Verificador de Phishing de Correo',
        checkerSubtitle: 'Pegue el contenido completo del correo electrónico o cargue un archivo de correo (.eml, .txt) para verificar amenazas de phishing.',
        pastePlaceholder: 'Pegue el contenido de su correo aquí...',
        uploadFile: 'Subir Archivo',
        analyze: 'Analizar Correo',
        analyzing: 'Analizando...',
        result: 'Resultado del Análisis',
        safe: 'Seguro',
        suspicious: 'Sospechoso',
        phishing: 'Phishing',
        poweredBy: 'Análisis impulsado por algoritmos de Random Forest y Blacklist con >98% de precisión.',
        error: 'Ocurrió un error durante el análisis. Por favor, inténtelo de nuevo.',
        logout: 'Cerrar Sesión',
    },
    FR: {
        title: 'Phishguard',
        login: 'Connexion',
        signup: 'S\'inscrire',
        email: 'Adresse E-mail',
        password: 'Mot de passe',
        noAccount: 'Vous n\'avez pas de compte ?',
        haveAccount: 'Vous avez déjà un compte ?',
        checkerTitle: 'Vérificateur de Phishing par E-mail',
        checkerSubtitle: 'Collez le contenu complet de l\'e-mail ou téléchargez un fichier d\'e-mail (.eml, .txt) pour vérifier les menaces de phishing.',
        pastePlaceholder: 'Collez le contenu de votre e-mail ici...',
        uploadFile: 'Télécharger le Fichier',
        analyze: 'Analyser l\'E-mail',
        analyzing: 'Analyse en cours...',
        result: 'Résultat de l\'Analyse',
        safe: 'Sûr',
        suspicious: 'Suspect',
        phishing: 'Hameçonnage',
        poweredBy: 'Analyse optimisée par des algorithmes Random Forest et Blacklist avec une précision de >98%.',
        error: 'Une erreur s\'est produite lors de l\'analyse. Veuillez réessayer.',
        logout: 'Déconnexion',
    },
};
